=== payalb/Hibernate/XmlDemo/family.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="family">
		<xsd:complexType>
			<!-- order of elements should be preserved -->
			<!-- <xsd:all > -->
			<xsd:sequence>
				<xsd:element name="member" maxOccurs="unbounded">
					<xsd:complexType>
						<!-- order of elements should be preserved -->
						<xsd:sequence>
							<xsd:group ref="group1" />

							<xsd:element name="dob">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}" />
									</xsd:restriction>

								</xsd:simpleType>

							</xsd:element>
							<xsd:element name="accomodation-type" default="House">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="House" />
										<xsd:enumeration value="Flat" />
										<xsd:enumeration value="Rented" />
									</xsd:restriction>


								</xsd:simpleType>


							</xsd:element>

							<xsd:element name="photo">

								<xsd:complexType>
									<xsd:attribute name="src" type="xsd:string" use="required" />
								</xsd:complexType>
							</xsd:element>


							<xsd:element name="country">

								<xsd:complexType mixed="true">

									<xsd:choice>
										<xsd:element name="city" type="xsd:string" />
										<xsd:element name="state" type="xsd:string" />
									</xsd:choice>

								</xsd:complexType>


							</xsd:element>

							<xsd:element name="hasVisa" type="xsd:boolean">

								<!-- true | false| 0 | 1 -->
							</xsd:element>
						</xsd:sequence>

					</xsd:complexType>

				</xsd:element>

				<!-- </xsd:all> -->
			</xsd:sequence>
		</xsd:complexType>



	</xsd:element>


	<xsd:group name="group1">
		<xsd:sequence>

			<xsd:element name="relationship" type="xsd:string" />
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="age">
				<xsd:simpleType>
					<xsd:restriction base="xsd:integer">
						<xsd:minInclusive value="40" />
						<xsd:maxInclusive value="60" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>

	</xsd:group>

</xsd:schema>

=== payalb/Hibernate/XmlDemo/Demo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="family.xsd">

<member>
<relationship>Father</relationship>
<name>A.K.Bansal</name>
<age>44</age>
<dob>12-12-1984</dob>
<accomodation-type></accomodation-type>
<photo src=""/>
<country> USA
<city>Meerut</city>
</country>  
<hasVisa>1</hasVisa>
</member>

<member>
<relationship>Mother</relationship>
<name>K.Bansal</name>
<age>60</age>
<dob>23-11-1984</dob>
<accomodation-type>Flat</accomodation-type>
<photo src=""/>
<country> India
<state>UP</state>
</country>
<hasVisa>0</hasVisa>
</member>
</family>
